// These aliases normalize map and provider names to the same restaurant label.
export const brandAliases = {
  "mcdonald's": "McDonald's",
  mcdonalds: "McDonald's",
  "burger king": "Burger King",
  "dunkin'": "Dunkin'",
  dunkin: "Dunkin'",
  "domino's": "Domino's",
  dominos: "Domino's",
  "pizza hut": "Pizza Hut",
  kfc: "KFC",
  sonic: "Sonic",
  "sonic drive-in": "Sonic",
  "dairy queen": "Dairy Queen",
  "little caesars": "Little Caesars",
  "chick-fil-a": "Chick-fil-A",
  chipotle: "Chipotle",
  "taco bell": "Taco Bell",
  subway: "Subway",
  panera: "Panera Bread",
  sweetgreen: "Sweetgreen",
  cava: "CAVA",
  "wendy's": "Wendy's",
  wendys: "Wendy's",
  starbucks: "Starbucks",
  qdoba: "QDOBA",
  "jersey mike's": "Jersey Mike's",
  "panda express": "Panda Express",
  popeyes: "Popeyes",
  "arby's": "Arby's",
  arbys: "Arby's",
  chopt: "Chopt",
  "chop't": "Chopt",
  "olive garden": "Olive Garden",
  "denny's": "Denny's",
  dennys: "Denny's",
  "five guys": "Five Guys",
  wingstop: "Wingstop",
  "raising cane's": "Raising Cane's",
  whataburger: "Whataburger",
  "jack in the box": "Jack in the Box",
  "jimmy john's": "Jimmy John's",
  ihop: "IHOP",
};

export const commonRestaurants = [...new Set(Object.values(brandAliases))];
